import type { Metadata } from "next";
import { Theme } from '@radix-ui/themes';
import { Inter } from "next/font/google";

import '@radix-ui/themes/styles.css';
import 'tldraw/tldraw.css';
import "./globals.css";
import AppProvider from "@/contexts/AppContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Whiteboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <AppProvider>
            {children}
          </AppProvider>
        </Theme>
      </body>
    </html>
  );
}
